Feature/module animation
CLENJOPOMI/EquinoxEngine pull request #106
Opened 2017-03-19 19:54 UTC by polvila

close #95

2017-03-19 20:02 UTC, jowie94 requested changes

2017-03-19 20:02 UTC, jowie94 commented on Equinox/ModuleAnimation.cpp
> +	const aiScene* scene = aiImportFile(filePath, aiProcessPreset_TargetRealtime_MaxQuality);
Once we finish using the scene, it has to be released using `aiReleaseImport`

2017-03-19 20:02 UTC, jowie94 commented on Equinox/ModuleAnimation.h
> +	std::vector<Channel> Channels;
Why don't we use pointers? Pointers ensure that we always use the same instance, not a copy

2017-03-19 20:02 UTC, jowie94 commented on Equinox/ModuleAnimation.h
> +	typedef std::map<std::string, Animation> AnimationsMap;
Ditto, maybe it's better to use pointers to avoid unnecessary copies

2017-03-20 19:34 UTC, theepsi approved these changes

2017-03-20 19:48 UTC, jowie94 approved these changes

2017-03-20 19:49 UTC, merged