Rename simple timer methods
CLENJOPOMI/EquinoxEngine pull request #15
Opened 2017-01-24 18:37 UTC by polvila

2017-01-26 16:05 UTC, theepsi commented on Equinox/SimpleTimer.h
> +	unsigned int Stop()
Stop is not working as expected, it must return the time when it was stopped, even if the timer is stopped. Bassically you just need to stop the timer and return Read();

2017-01-26 16:08 UTC, theepsi commented on Equinox/SimpleTimer.h
> +	unsigned int Read() const
What happens is you call Read when the timer is stopped? you must return the time when it was stopped. Here you are returning 0 if the timer is stopped such is not correct.

2017-01-26 16:09 UTC, theepsi requested changes
There are still a lot of logic we dont need, please try to do it just like the complexTimer

2017-01-26 22:06 UTC, jowie94 commented
Still more functionality than expected by the complex API, but acceptable. Please change header guards to be __SIMPLETIMER_H__ instead of __TIMER_H__

2017-01-26 22:07 UTC, jowie94 requested changes
Still more functionality than expected by the complex API, but acceptable. Please change header guards to be SIMPLETIMER_H instead of TIMER_H

2017-02-03 17:41 UTC, theepsi approved these changes

2017-02-05 10:13 UTC, jowie94 commented on Equinox/SimpleTimer.h
>  	unsigned int Read() const
Read now is not correctly implemented, it must always return the elapsed time if running, or the elapsed time when until the timer was stopped. Please check the complex timer implementation: https://github.com/NeebulaGames/EquinoxEngine/blob/feature/testing-timers/Equinox/ComplexTimer.h

2017-02-05 10:13 UTC, jowie94 requested changes
Read now is not correctly implemented, it must always return the elapsed time if running, or the elapsed time when until the timer was stopped. Please check the complex timer implementation: https://github.com/NeebulaGames/EquinoxEngine/blob/feature/testing-timers/Equinox/ComplexTimer.h

2017-02-05 12:01 UTC, jowie94 commented on Equinox/SimpleTimer.h
> +		ticks = ticks - SDL_GetTicks();
If the timer is already stopped it will be updating the running ticks each time we call stop. It can be substituted with a call to Read()

2017-02-08 13:46 UTC, jowie94 requested changes
You can't modify complex timer here!

2017-02-08 13:47 UTC, theepsi requested changes
why did you modified complex timer? is not the the purpose of this branch...

2017-02-10 10:33 UTC, theepsi approved these changes

2017-02-10 10:44 UTC, jowie94 approved these changes

2017-02-10 10:58 UTC, merged